name: Latest blog post workflow
on:
  schedule: # Run workflow automatically
    - cron: '30 0 * * 0'
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the GitHub Actions Workflow page directly
permissions:
  contents: write # To write the generated contents to the readme

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Fetch Medium Blogs
        id: fetch_medium_blogs
        run: |
          MEDIUM_USERNAME=21pa1a0593
          BLOGS=$(curl -s "https://api.rss2json.com/v1/api.json?rss_url=https://medium.com/feed/@${MEDIUM_USERNAME}" | jq -r '.items | map({title, link}) | .[] | " - [\(.title)](\(.link))"')
          echo "$BLOGS" > blogs.md
          echo "::set-output name=blogs::$BLOGS"

      - name: Update README
        run: |
          BLOGS=$(cat blogs.md)
          awk -v blogs="$BLOGS" 'BEGIN {found=0} \
          /<!-- BLOG-POST-LIST:START -->/ {print; print blogs; found=1; next} \
          /<!-- BLOG-POST-LIST:END -->/ {found=0} \
          !found {print}' README.md > README.tmp && mv README.tmp README.md

      - name: Commit changes
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add README.md
          git commit -m 'Update README with latest Medium blogs'
          git pull --rebase origin main
          git push https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }}.git
