name: Update README with Latest Medium Blogs
on:
  schedule:
    - cron: '30 0 * * 0'
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Fetch Medium Blogs
      - name: Fetch Medium Blogs
        id: fetch_medium_blogs
        run: |
          MEDIUM_USERNAME=21pa1a0593
          BLOGS=$(curl -s "https://api.rss2json.com/v1/api.json?rss_url=https://medium.com/feed/@${MEDIUM_USERNAME}" | jq -r '.items[0:3] | map({title, link}) | .[] | " - [\(.title)](\(.link))"')
          echo "$BLOGS" > blogs.md
          echo "::set-output name=blogs::$BLOGS"

      # Step 3: Update README.md
      - name: Update README
        run: |
          BLOGS=$(cat blogs.md)
          awk -v blogs="$BLOGS" 'BEGIN {found=0} \
          /<!--START_SECTION:medium_blogs-->/ {print; print blogs; found=1; next} \
          /<!--END_SECTION:medium_blogs-->/ {found=0} \
          !found {print}' README.md > README.tmp && mv README.tmp README.md

      # Step 4: Commit changes to the repository
      - name: Commit changes
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add README.md
          git commit -m 'Update README with latest Medium blogs'
          git push https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }}.git
